
lookUp004B = {
    'gib': 'Bauwerk',
    'gik': 'Gebietskörperschaft, Verwaltungseinheit',
    'gif': 'Gliedstaat',
    'gil': 'Land, Staat',
    'giv': 'Verwaltungseinheit',
    'gir': 'Religiöse Verwaltungseinheit',
    'kiv': 'Religiöse Verwaltungseinheit',
    'gin': 'Natürliche geografische Einheit',
    'gio': 'Kleinräumiges Geografikum',
    'giw': 'Grenze, Weg, Linie',
    'gix': 'Extraterrestrikum',
    'giz': 'Geografikum',
    'gxz': 'Fiktiver Ort',
    'kif': 'Firma',
    'kim': 'Musikalische Körperschaft',
    'kio': 'Organ einer Gebietskörperschaft',
    'kip': 'Projekt',
    'kir': 'Religiöse Körperschaft',
    'kiz': 'Organisation',
    'uiz': 'Organisation',
    'kxz': 'Fiktive Organisation',
    'pif': 'Familie',
    'pik': 'Mitglied regierender Fürstenhäuser',
    'pip': 'Pseudonym',
    'pis': 'Pseudonym',
    'piz': 'Person',
    'pxg': 'Gott',
    'pxl': 'Literarische Gestalt, Sagengestalt',
    'pxs': 'Geist',
    'sab': 'Musikalische Besetzung',
    'sad': 'Datenträger',
    'sag': 'Musikalisches Genre',
    'saz': 'Allgemeinbegriff',
    'sie': 'Ethnografikum',
    'sif': 'Verkehrsmittel mit Individualnamen',
    'sih': 'Historisches Einzelereignis',
    'sip': 'Produkt, Markenname',
    'sis': 'Sprache',
    'siu': 'Personengruppe',
    'siw': 'Softwareprodukt',
    'siz': 'Sachbegriff mit Individualnamen',
    'slz': 'Buchstabe, Morphem, Wort',
    'snz': 'Nomenklatur (Biologie / Chemie)',
    'szz': '',
    'sxz': 'Fiktiver Sachbegriff',
    'vie': 'Veranstaltung',
    'vif': 'Veranstaltungsfolge',
    'wid': 'Druckermarke',
    'wie': 'Expression',
    'wif': 'Fassung eines Werks der Musik',
    'wim': 'Werk der Musik',
    'win': 'Sammlung',
    'wip': 'Provenienzmerkmal',
    'wis': 'Schriftdenkmal',
    'wit': 'Werk'
}

lookupSachgruppe = {
    '000': 'Allgemeines, Wissenschaft',
    '004': 'Informatik',
    '010': 'Bibliografien',
    '020': 'Bibliotheks - und Informationswissenschaft',
    '030': 'Enzyklopädien',
    '050': 'Zeitschriften, fortlaufende Sammelwerke',
    '060': 'Organisationen, Museumswissenschaft',
    '070': 'Nachrichtenmedien, Journalismus, Verlagswesen',
    '080': 'Allgemeine Sammelwerke',
    '090': 'Handschriften, seltene Bücher',
    '100': 'Philosophie',
    '130': 'Parapsychologie, Okkultismus',
    '150': 'Psychologie',
    '200': 'Religion, Religionsphilosophie',
    '220': 'Bibel',
    '230': 'Theologie, Christentum',
    '290': 'Andere Religionen',
    '300': 'Sozialwissenschaften, Soziologie, Anthropologie',
    '310': 'Statistik',
    '320': 'Politik',
    '330': 'Wirtschaft',
    '333.7': 'Natürliche Ressourcen, Energie und Umwelt',
    '340': 'Recht',
    '350': 'Öffentliche Verwaltung',
    '355': 'Militär',
    '360': 'Soziale Probleme, Sozialdienste, Versicherungen',
    '370': 'Erziehung, ç - und Bildungswesen',
    '380': 'Handel, Kommunikation, Verkehr',
    '390': 'Bräuche, Etikette, Folklore',
    '400': 'Sprache, Linguistik',
    '420': 'Englisch',
    '430': 'Deutsch',
    '439': 'Andere germanische Sprachen',
    '440': 'Französisch, romanische Sprachen allgemein',
    '450': 'Italienisch, Rumänisch, Rätoromanisch',
    '460': 'Spanisch, Portugiesisch',
    '470': 'Latein',
    '480': 'Griechisch',
    '490': 'Andere Sprachen',
    '491.8': 'Slawische Sprache',
    '500': 'Naturwissenschaften',
    '510': 'Mathematik',
    '520': 'Astronomie, Kartografie',
    '530': 'Physik',
    '540': 'Chemie',
    '550': 'Geowissenschaften',
    '560': 'Paläontologie',
    '570': 'Biowissenschaften, Biologie',
    '580': 'Pflanzen(Botanik)',
    '590': 'Tiere(Zoologie)',
    '600': 'Technik',
    '610': 'Medizin, Gesundheit',
    '620': 'Ingenieurwissenschaften und Maschinenbau',
    '621.3': 'Elektrotechnik, Elektronik',
    '624': 'Ingenieurbau und Umwelttechnik',
    '630': 'Landwirtschaft, Veterinärmedizin',
    '640': 'Hauswirtschaft und Familienleben',
    '650': 'Management',
    '660': 'Technische Chemie',
    '670': 'Industrielle und handwerkliche Fertigung',
    '690': 'Hausbau, Bauhandwerk',
    '700': 'Künste, Bildende Kunst allgemein',
    '710': 'Landschaftsgestaltung, Raumplanung',
    '720': 'Architektur',
    '730': 'Plastik, Numismatik, Keramik, Metallkunst',
    '740': 'Zeichnung, Kunsthandwerk',
    '741.5': 'Comics, Cartoons, Karikaturen',
    '750': 'Malerei',
    '760': 'Grafische Verfahren, Drucke',
    '770': 'Fotografie, Computerkunst',
    '780': 'Musik',
    '780.2': 'Texte zu Musik',
    '780.7': 'Unterrichtswerke',
    '780.9': 'Sammlungen und Sammelwerke aus verschiedenen Bereichen, Großausgaben',
    '781': 'Musik nach Gattungen',
    '781.54': 'Background Music',
    '781.542': 'Filmmusik',
    '781.556': 'Ballettmusik',
    '781.62': 'Volksmusik',
    '781.64': 'Unterhaltungs -, Pop - und Rockmusik',
    '781.65': 'Jazz',
    '782': 'Vokalmusik',
    '782.1': 'Musikalische Bühnenwerke',
    '782.22': 'Geistliche Vokalmusik',
    '782.25': 'Geistliche Lieder',
    '782.4': 'Weltliche Vokalmusik',
    '782.5': 'Chormusik für gemischte Stimmen',
    '782.6': 'Chormusik für Frauenstimmen',
    '782.7': 'Chormusik für Kinder - und Jugendstimmen',
    '782.8': 'Chormusik für Männerstimmen',
    '783': 'Vokalmusik für Einzelstimmen',
    '783.1': 'Lieder',
    '784.2': 'Musik für Orchester',
    '784.23': 'Konzerte für Soloinstrument(e) und Orchester',
    '784.9': 'Blasorchester',
    '785': 'Kammermusik',
    '785.12': 'Duos',
    '785.13': 'Trios',
    '785.14': 'Quartette',
    '785.15': 'Quintette und mehr',
    '786': 'Tasten - und Schlaginstrumente, mechanische und elektronische Instrumente',
    '786.2': 'Klavier',
    '786.4': 'Cembalo',
    '786.5': 'Orgel',
    '786.6': 'Mechanische Instrumente',
    '786.7': 'Elektronische Instrumente',
    '786.8': 'Schlaginstrumente',
    '787': 'Streich - und Zupfinstrumente',
    '787.2': 'Violine',
    '787.3': 'Viola',
    '787.4': 'Violoncello',
    '787.5': 'Kontrabass',
    '787.6': 'Andere Streichinstrumente',
    '787.7': 'Zupfinstrumente',
    '787.9': 'Harfe',
    '788': 'Blasinstrumente',
    '788.3': 'Flöten',
    '788.4': 'Rohrblattinstrumente',
    '788.8': 'Akkordeon, Mundharmonika',
    '788.92': 'Trompete',
    '788.93': 'Posaune',
    '788.94': 'Horn',
    '788.96': 'Kornett',
    '788.97': 'Flügelhorn',
    '788.98': 'Tuba',
    '788.99': 'Andere Blechblasinstrumente',
    '790': 'Freizeitgestaltung, Darstellende Kunst',
    '791': 'Öffentliche Darbietungen, Film, Rundfunk',
    '792': 'Theater, Tanz',
    '793': 'Spiel',
    '796': 'Sport',
    '800': 'Literatur, Rhetorik, Literaturwissenschaft',
    '810': 'Englische Literatur Amerikas',
    '820': 'Englische Literatur',
    '830': 'Deutsche Literatur',
    '839': 'Literatur in anderen germanischen Sprachen',
    '840': 'Französische Literatur',
    '850': 'Italienische, rumänische, rätoromanische Literatur',
    '860': 'Spanische und portugiesische Literatur',
    '870': 'Lateinische Literatur',
    '880': 'Griechische Literatur',
    '890': 'Literatur in anderen Sprachen',
    '891.8': 'Slawische Literatur',
    '900': 'Geschichte',
    '910': 'Geografie, Reisen',
    '914.3': 'Geografie, Reisen(Deutschland)',
    '920': 'Biografie, Genealogie, Heraldik',
    '930': 'Alte Geschichte, Archäologie',
    '940': 'Geschichte Europas',
    '943': 'Geschichte Deutschlands',
    '950': 'Geschichte Asiens',
    '960': 'Geschichte Afrikas',
    '970': 'Geschichte Nordamerikas',
    '980': 'Geschichte Südamerikas',
    '990': 'Geschichte der übrigen Welt',
    'B': 'Belletristik',
    'K': 'Kinder - und Jugendliteratur',
    'S': 'Schulbücher',
    '914.94': 'Geografie, Reisen(Schweiz)',
    '914.36': 'Geografie, Reisen(Österreich)',
    '949.4': 'Geschichte der Schweiz',
    '943.6': 'Geschichte Österreichs'
}
